FROM cassandra:3.11
# package manager apt-get

# RUN useradd -ms /bin/bash user

WORKDIR /
COPY . /
# RUN ["chmod", "+x", "/ca ss.sh"]

# USER user
# RUN service cassandra start

# RUN sleep 500
# USER user
# RUN cqlsh -e "SOURCE 'cass.sql'"

# RUN ./cass.sh
